name: gproject
description: تطبيق شكاوى المواطنين
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  file_picker: ^5.2.0
  cloud_firestore: ^6.2.0
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.6.2
  geolocator: ^14.0.2
  geocoding: ^2.2.0

  image_picker: ^1.0.0
  firebase_storage: 13.2.0

  # التصدير
  printing: ^5.13.1
  pdf: ^3.10.7
  excel: ^4.0.6
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
