// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4pagavO1UMIhnDyLF3GTVjFvFWVVAQG8',
    appId: '1:577135514195:web:6add27369c061c8dc46ca6',
    messagingSenderId: '577135514195',
    projectId: 'gproject-37f76',
    authDomain: 'gproject-37f76.firebaseapp.com',
    storageBucket: 'gproject-37f76.firebasestorage.app',
    measurementId: 'G-KVBEFWT5TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGtliISXmm5Ddz3ECKbvYQ4phFChFPeto',
    appId: '1:577135514195:android:16763f4fc70d71a2c46ca6',
    messagingSenderId: '577135514195',
    projectId: 'gproject-37f76',
    storageBucket: 'gproject-37f76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzvmCyyapE1NDxhJSk33R0ZfZQU2il1gA',
    appId: '1:577135514195:ios:1878db97f9502ecac46ca6',
    messagingSenderId: '577135514195',
    projectId: 'gproject-37f76',
    storageBucket: 'gproject-37f76.firebasestorage.app',
    iosBundleId: 'com.atheer.gprojcet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzvmCyyapE1NDxhJSk33R0ZfZQU2il1gA',
    appId: '1:577135514195:ios:1878db97f9502ecac46ca6',
    messagingSenderId: '577135514195',
    projectId: 'gproject-37f76',
    storageBucket: 'gproject-37f76.firebasestorage.app',
    iosBundleId: 'com.atheer.gprojcet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4pagavO1UMIhnDyLF3GTVjFvFWVVAQG8',
    appId: '1:577135514195:web:1ff8c5f00fb8eee7c46ca6',
    messagingSenderId: '577135514195',
    projectId: 'gproject-37f76',
    authDomain: 'gproject-37f76.firebaseapp.com',
    storageBucket: 'gproject-37f76.firebasestorage.app',
    measurementId: 'G-4S0QHV5T66',
  );
}
